# Gunakan image Node.js versi ringan
FROM node:18-alpine

# Set folder kerja
WORKDIR /app

# Copy package.json
COPY package*.json ./

# Install dependencies frontend
RUN npm install

# Copy sisa kode frontend
COPY . .

# Expose port React (default 3000)
EXPOSE 3000

# Environment variable agar React jalan normal di Docker
ENV CI=true
ENV WDS_SOCKET_PORT=0

# Perintah menjalankan React
CMD ["npm", "start"]